# Version of the config. Do not change!
Config-Version: 3
# Debag used to search for items and containers with the help of which potential dupes can be performed.
Debug: false
# When the 'Enable' parameter is changed, a server reboot is required.
# Parameters for the listener throwing items.
FixContainer:
    Enable: false
    ItemList:
        # If true, then the list below will be considered black, otherwise white.
        BlackList: true
        # List of items.
        List:
            - "forestry:portable_alyzer"
            - "forestry:adventurer_bag"
            - "forestry:adventurer_bag_t2"
            - "forestry:apiarist_bag"
            - "forestry:lepidopterist_bag"
            - "forestry:miner_bag"
            - "forestry:miner_bag_t2"
            - "forestry:digger_bag"
            - "forestry:digger_bag_t2"
            - "forestry:forester_bag"
            - "forestry:forester_bag_t2"
            - "forestry:hunter_bag"
            - "forestry:hunter_bag_t2"
            - "forestry:builder_bag"
            - "forestry:builder_bag_t2"
            - "botany:botanist_bag"
    ContainerList:
        # If true, then the list below will be considered black, otherwise white.
        BlackList: false
        # List of container names.
        List:
            - ContainerPlayer
            - ContainerChest
            - ContainerShulkerBox
    Messages:
        SendToPlayer: true
        Console: "&cPlayer &b%player% &ctrying to dupe using an item with id &a%item_id%&c."
        Player: "&4Sorry, but this dupe is no longer working for us..."
        Debug: "&ePlayer &b%player% &ethrown item &f- &a%item%&e. Open container ID &f- &a%сontainer%&e."
# Works only with GriefPrevention!
# This is a fix of fluids in claim in which the player does not have rights to interact with the block, but can use items.
FixFluidDupe:
    Enable: false
    ItemList:
        # Blacklist items.
        List:
            - "minecraft:bucket"
            - "minecraft:glass_bottle"
    Messages:
        SendToPlayer: true
        Console: "&cPlayer &b%player% &ctried to dupe the fluid along the coordinates &f- &a%coordinates%&c."
        Player: "&4Sorry, but this dupe is no longer working for us..."
# Cancels a click on a subject with the Shift key held down.
BlockShiftClick:
    Enable: false
    ItemList:
        # If true, then the list below will be considered black, otherwise white.
        BlackList: true
        # List of items.
        List:
            - "geneticsreborn:organicmatter"
    ContainerList:
        # If true, then the list below will be considered black, otherwise white.
        BlackList: true
        # List of container names.
        List:
            - "ContainerCellAnalyser"
    Messages:
        SendToPlayer: true
        Console: "&cPlayer &b%player% &ctrying to dupe using an item with id &a%item_id%&c."
        Player: "&4Sorry, but in this container this action is prohibited."
        Debug: "&ePlayer &b%player% &euse ShiftClick with item &f- &a%item%&e. Open container ID &f- &a%сontainer%&e."
PortalLock:
    Enable: false
    # Worlds in which teleportation will be blocked
    AllWorlds: true
    BlockTeleportation:
        Items: true
        Mobs: false
        Players: false
    ExampleWorld1:
        BlockTeleportation:
            Items: true
            Mobs: false
            Players: false
    ExampleWorld2:
        BlockTeleportation:
            Items: true
            Mobs: true
            Players: false
